<?php
/**
 * Language labels for database tables/fields belonging to extension "maag_randomimage"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
    'tt_content.list_type_pi1' => 'Random Images',	
    'tt_content.pi_flexform.sheet_general' => 'General', 
    'tt_content.pi_flexform.sheet_general.uniqueKey' => 'Unique key of plugin', 
    'tt_content.pi_flexform.sheet_general.path' => 'Image Path', 
    'tt_content.pi_flexform.sheet_general.bigImagePath' => 'Big Image Path', 
    'tt_content.pi_flexform.sheet_general.ignore' => 'Ignore Path (comma-separated)', 
    'tt_content.pi_flexform.sheet_general.ignorefolder' => 'Ignore Folders (comma-separated)', 
    'tt_content.pi_flexform.sheet_general.ignorefile' => 'Ignore Files (comma-separated)', 
    'tt_content.pi_flexform.sheet_general.useImagemagick' => 'Use Imagemagick to resize Images', 
    'tt_content.pi_flexform.sheet_general.imageMagickParams' => 'Params for imagemagick', 
    'tt_content.pi_flexform.sheet_general.imageMagickParamsBigImage' => 'Params for imagemagick for big image', 
    'tt_content.pi_flexform.sheet_general.imageMagickCommand' => 'Imagemagick command', 
    'tt_content.pi_flexform.sheet_general.imageMagickCommandParams' => 'Imagemagick command params',
    'tt_content.pi_flexform.sheet_general.imageMagickCommandBigImage' => 'Imagemagick command for big image', 
    'tt_content.pi_flexform.sheet_general.imageMagickCommandBigImageParams' => 'Imagemagick command params for big image',
    'tt_content.pi_flexform.sheet_general.httpsBackend' => 'Using Typo3 Backend over SSL', 
	'tt_content.pi_flexform.sheet_display' => 'Display', 
    'tt_content.pi_flexform.sheet_display.dynamic' => 'Dynamic Change', 
    'tt_content.pi_flexform.sheet_display.imageFading' => 'Change with fading effect', 
    'tt_content.pi_flexform.sheet_display.imageFadingStyle' => 'Style of Imagefading Div', 
    'tt_content.pi_flexform.sheet_display.count' => 'Count of Images', 
    'tt_content.pi_flexform.sheet_display.interval' => 'Interval (in Miliseconds)', 
    'tt_content.pi_flexform.sheet_display.recursive' => 'Recursive', 
    'tt_content.pi_flexform.sheet_display.altText' => 'Image alt', 
	'tt_content.pi_flexform.sheet_display.titleText' => 'Image title', 
    'tt_content.pi_flexform.sheet_display.caption' => 'Image Caption', 
    'tt_content.pi_flexform.sheet_display.imageCaptionStyle' => 'Image Caption Style', 
    'tt_content.pi_flexform.sheet_display.stdwrap' => 'Extension wrap', 
    'tt_content.pi_flexform.sheet_display.wrap' => 'Image wrap', 
    'tt_content.pi_flexform.sheet_display.link' => 'Image link', 
    'tt_content.pi_flexform.sheet_display.sort' => 'Sort', 
    'tt_content.pi_flexform.sheet_display.sort.1' => 'unsorted', 
    'tt_content.pi_flexform.sheet_display.sort.2' => 'Sorted by Filedate', 
    'tt_content.pi_flexform.sheet_display.sort.3' => 'Sorted by Filename (without path)', 
    'tt_content.pi_flexform.sheet_display.sort.4' => 'Sorted by Filename (within path)', 
    'tt_content.pi_flexform.sheet_display.sortorder' => 'Sort Order', 
    'tt_content.pi_flexform.sheet_display.sortorder.1' => 'ascending', 
    'tt_content.pi_flexform.sheet_display.sortorder.2' => 'descending', 
    'tt_content.pi_flexform.sheet_display.sortOnDynamicChange' => 'Sort images also on dynamic changes', 
    'tt_content.pi_flexform.sheet_display.maxwidth' => 'Max width of image', 
    'tt_content.pi_flexform.sheet_display.maxheight' => 'Max height of image', 
    'tt_content.pi_flexform.sheet_hovereffect' => 'Hover Effect', 
    'tt_content.pi_flexform.sheet_hovereffect.showBigImageOnHover' => 'Show big image on mouse hover', 
    'tt_content.pi_flexform.sheet_hovereffect.hideBigImageOnOut' => 'Hide big image on mouse out', 
    'tt_content.pi_flexform.sheet_hovereffect.changeBigImage' => 'Change Big Image if small Image changes', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft' => 'Position from left', 
    'tt_content.pi_flexform.sheet_hovereffect.marginLeft' => 'Margin from left position', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop' => 'Position from top', 
    'tt_content.pi_flexform.sheet_hovereffect.marginTop' => 'Margin from top position', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.1' => 'relative from right margin of small image', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.2' => 'fixed from left margin of browser', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.3' => 'relative from left margin of first image', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.1' => 'relative from top margin of small image', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.2' => 'fixed from top margin of browser', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.3' => 'relative from top margin of first image', 
    'tt_content.pi_flexform.sheet_hovereffect.loadingImageText' => 'Text for Image Loading', 
    'tt_content.pi_flexform.sheet_hovereffect.loadingImageStyle' => 'Style for Text Image Loading', 
    'tt_content.pi_flexform.sheet_hovereffect.bigImageWrap' => 'Wrap of big Image', 
    'tt_content.pi_flexform.sheet_bigimage' => 'Big Image', 
    'tt_content.pi_flexform.sheet_bigimage.displayonload' => 'Show big image on page load', 
    'tt_content.pi_flexform.sheet_bigimage.imagenumber' => 'Number of shown small images, begin by 1 (0 for random)', 
    'tt_content.pi_flexform.sheet_bigimage.imagename' => 'Image path and name (if not in small images)', 
    'tt_content.pi_flexform.sheet_display.bigimagemaxwidth' => 'Max width of big image', 
    'tt_content.pi_flexform.sheet_display.bigimagemaxheight' => 'Max height of big image', 
    'tt_content.pi_flexform.sheet_debug' => 'Debugging', 
    'tt_content.pi_flexform.sheet_debug.showdebuginfo' => 'Show Debug Infos', 
	),
	'de' => Array (
	'tt_content.list_type_pi1' => 'Random Images',	
    'tt_content.pi_flexform.sheet_general.uniqueKey' => 'Eindeutige Identifikation des Plugins', 
    'tt_content.pi_flexform.sheet_general' => 'Allgemeine Einstellungen', 
    'tt_content.pi_flexform.sheet_general.path' => 'Bilder-Pfad', 
    'tt_content.pi_flexform.sheet_general.bigImagePath' => 'Bilder-Pfad für grosse Bilder', 
    'tt_content.pi_flexform.sheet_general.ignore' => 'Pfad ignorieren (Komma-getrennt)', 
    'tt_content.pi_flexform.sheet_general.ignorefolder' => 'Ordner ignorieren (Komma-getrennt)', 
    'tt_content.pi_flexform.sheet_general.ignorefile' => 'Dateien ignorieren (Komma-getrennt)', 
    'tt_content.pi_flexform.sheet_general.useImagemagick' => 'Imagemagick zur Grössenänderung benutzen', 
    'tt_content.pi_flexform.sheet_general.imageMagickParams' => 'Parameter für Imagemagick', 
    'tt_content.pi_flexform.sheet_general.imageMagickParamsBigImage' => 'Parameter für Imagemagick (Grosses Bild)', 
    'tt_content.pi_flexform.sheet_general.imageMagickCommand' => 'Imagemagick Kommando', 
	'tt_content.pi_flexform.sheet_general.imageMagickCommandParams' => 'Imagemagick Kommando Parameter',
    'tt_content.pi_flexform.sheet_general.imageMagickCommandBigImage' => 'Imagemagick Kommando (Grosses Bild)', 
	'tt_content.pi_flexform.sheet_general.imageMagickCommandBigImageParams' => 'Imagemagick Kommando Parameter (Grosses Bild)',
    'tt_content.pi_flexform.sheet_general.httpsBackend' => 'Typo3 Backend über SSL', 
	'tt_content.pi_flexform.sheet_display' => 'Anzeige', 
    'tt_content.pi_flexform.sheet_display.dynamic' => 'Dynamischer Wechsel', 
    'tt_content.pi_flexform.sheet_display.imageFading' => 'Wechsel mit Überblendeffekt', 
    'tt_content.pi_flexform.sheet_display.imageFadingStyle' => 'Style des Imagefading Divs', 
    'tt_content.pi_flexform.sheet_display.count' => 'Anzahl Bilder', 
    'tt_content.pi_flexform.sheet_display.interval' => 'Intervall (in Millisekunden)', 
    'tt_content.pi_flexform.sheet_display.recursive' => 'Rekursiv', 
    'tt_content.pi_flexform.sheet_display.altText' => 'Bild-Name (alt=)', 
	'tt_content.pi_flexform.sheet_display.titleText' => 'Bild-Titel (title=)', 
    'tt_content.pi_flexform.sheet_display.caption' => 'Bild-Unterschrift (caption)', 
    'tt_content.pi_flexform.sheet_display.imageCaptionStyle' => 'Style von Bild-Unterschrift', 
    'tt_content.pi_flexform.sheet_display.stdwrap' => 'Wrap um Extension', 
    'tt_content.pi_flexform.sheet_display.wrap' => 'Wrap um Image', 
    'tt_content.pi_flexform.sheet_display.link' => 'Link um Image', 
    'tt_content.pi_flexform.sheet_display.sort' => 'Sortierung', 
    'tt_content.pi_flexform.sheet_display.sort.1' => 'unsortiert', 
    'tt_content.pi_flexform.sheet_display.sort.2' => 'Sortiert nach Dateidatum', 
    'tt_content.pi_flexform.sheet_display.sort.3' => 'Sortiert nach Dateiname (ohne Pfad)', 
    'tt_content.pi_flexform.sheet_display.sort.4' => 'Sortiert nach Dateiname (mit Pfad)', 
    'tt_content.pi_flexform.sheet_display.sortorder' => 'Sortierreihenfolge', 
    'tt_content.pi_flexform.sheet_display.sortorder.1' => 'aufsteigend', 
    'tt_content.pi_flexform.sheet_display.sortorder.2' => 'absteigend', 
    'tt_content.pi_flexform.sheet_display.sortOnDynamicChange' => 'Bilder auch beim dynamischen Wechseln sortieren', 
    'tt_content.pi_flexform.sheet_display.maxwidth' => 'Max. Breite des Bildes', 
    'tt_content.pi_flexform.sheet_display.maxheight' => 'Max. Höhe des Bildes', 
    'tt_content.pi_flexform.sheet_hovereffect' => 'Maus-Over Effekt', 
    'tt_content.pi_flexform.sheet_hovereffect.showBigImageOnHover' => 'Zeige grosses Bild wenn Maus darüber fährt', 
    'tt_content.pi_flexform.sheet_hovereffect.hideBigImageOnOut' => 'Verstecke grosses Bild wenn Maus weg fährt', 
    'tt_content.pi_flexform.sheet_hovereffect.changeBigImage' => 'Wenn das kleine Bild wechselt, auch das grosse Bild wechseln', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft' => 'Position von links', 
    'tt_content.pi_flexform.sheet_hovereffect.marginLeft' => 'Rand von linker Position', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop' => 'Position von oben', 
    'tt_content.pi_flexform.sheet_hovereffect.marginTop' => 'Rand von oberer Position', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.1' => 'Relativ vom rechten Rand des kleinen Bildes', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.2' => 'Fix vom linken Rand des Browsers', 
    'tt_content.pi_flexform.sheet_hovereffect.positionLeft.3' => 'Relativ vom linken Rand des 1. kleinen Bildes', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.1' => 'Relativ vom oberen Rand des kleinen Bildes', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.2' => 'Fix vom oberen Rand des Browsers', 
    'tt_content.pi_flexform.sheet_hovereffect.positionTop.3' => 'Relativ vom oberen Rand des 1. kleinen Bildes', 
    'tt_content.pi_flexform.sheet_hovereffect.loadingImageText' => 'Text Bild wird geladen', 
    'tt_content.pi_flexform.sheet_hovereffect.loadingImageStyle' => 'Style für Text Bild wird geladen', 
    'tt_content.pi_flexform.sheet_hovereffect.bigImageWrap' => 'Wrap um grosses Bild', 
    'tt_content.pi_flexform.sheet_bigimage' => 'Grosses Bild', 
    'tt_content.pi_flexform.sheet_bigimage.displayonload' => 'Zeige grosses Bild wenn Seite geladen wird', 
    'tt_content.pi_flexform.sheet_bigimage.imagenumber' => 'Nummer der angezeigten kleinen Bilder beginnend bei 1 (0 = Zufall)', 
    'tt_content.pi_flexform.sheet_bigimage.imagename' => 'Bild Pfad und Name (wenn nicht unter den kleinen Bilder)', 
    'tt_content.pi_flexform.sheet_display.bigimagemaxwidth' => 'Max. Breite des grossen Bildes', 
    'tt_content.pi_flexform.sheet_display.bigimagemaxheight' => 'Max. Höhe des grossen Bildes', 
    'tt_content.pi_flexform.sheet_debug' => 'Debugging', 
    'tt_content.pi_flexform.sheet_debug.showdebuginfo' => 'Debug Infos anzeigen', 
  ),
);
?>