<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb1af944f0cc5ab226de341e528493365
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
        '023d27dca8066ef29e6739335ea73bad' => __DIR__ . '/..' . '/symfony/polyfill-php70/bootstrap.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '155488b065c09907a03c24fc72a78307' => __DIR__ . '/..' . '/lokielse/omnipay-alipay/src/Common/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'y' => 
        array (
            'yandexmoney\\YandexMoney\\' => 24,
        ),
        'T' => 
        array (
            'TrueBV\\' => 7,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php70\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\EventDispatcher\\' => 34,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'O' => 
        array (
            'Omnipay\\WorldPay\\' => 17,
            'Omnipay\\Wirecard\\' => 17,
            'Omnipay\\WechatPay\\' => 18,
            'Omnipay\\WebMoney\\' => 17,
            'Omnipay\\WePay\\' => 14,
            'Omnipay\\Veritrans\\' => 18,
            'Omnipay\\UnionPay\\' => 17,
            'Omnipay\\TwoCheckout\\' => 20,
            'Omnipay\\TargetPay\\' => 18,
            'Omnipay\\Stripe\\' => 15,
            'Omnipay\\Sisow\\' => 14,
            'Omnipay\\Sermepa\\' => 16,
            'Omnipay\\SecureTrading\\' => 22,
            'Omnipay\\SecurePay\\' => 18,
            'Omnipay\\SecPay\\' => 15,
            'Omnipay\\SagePay\\' => 16,
            'Omnipay\\Postfinance\\' => 20,
            'Omnipay\\Posnet\\' => 15,
            'Omnipay\\Portmanat\\' => 18,
            'Omnipay\\Pin\\' => 12,
            'Omnipay\\Paytrace\\' => 17,
            'Omnipay\\Paysafecard\\' => 20,
            'Omnipay\\Payone\\' => 15,
            'Omnipay\\PaymentWall\\' => 20,
            'Omnipay\\PaymentExpress\\' => 23,
            'Omnipay\\Payflow\\' => 16,
            'Omnipay\\PayU\\' => 13,
            'Omnipay\\PayPro\\' => 15,
            'Omnipay\\PayPal\\' => 15,
            'Omnipay\\PayFast\\' => 16,
            'Omnipay\\Pagarme\\' => 16,
            'Omnipay\\Oppwa\\' => 14,
            'Omnipay\\Novalnet\\Tests\\' => 23,
            'Omnipay\\Novalnet\\' => 17,
            'Omnipay\\Neteller\\' => 17,
            'Omnipay\\Netaxept\\' => 17,
            'Omnipay\\NetBanx\\' => 16,
            'Omnipay\\NestPay\\' => 16,
            'Omnipay\\NMI\\' => 12,
            'Omnipay\\Multicards\\' => 19,
            'Omnipay\\MultiSafepay\\' => 21,
            'Omnipay\\Mollie\\' => 15,
            'Omnipay\\MobilPay\\' => 17,
            'Omnipay\\Migs\\' => 13,
            'Omnipay\\Manual\\' => 15,
            'Omnipay\\MOLPay\\' => 15,
            'Omnipay\\Komoju\\' => 15,
            'Omnipay\\Ifthenpay\\' => 18,
            'Omnipay\\Helcim\\' => 15,
            'Omnipay\\Gvp\\' => 12,
            'Omnipay\\GoCardless\\' => 19,
            'Omnipay\\GlobalAlipay\\' => 21,
            'Omnipay\\GiroCheckout\\' => 21,
            'Omnipay\\Flo2cash\\' => 17,
            'Omnipay\\FirstData\\' => 18,
            'Omnipay\\Fatzebra\\' => 17,
            'Omnipay\\Fasapay\\' => 16,
            'Omnipay\\Eway\\' => 13,
            'Omnipay\\Dummy\\' => 14,
            'Omnipay\\Datatrans\\' => 18,
            'Omnipay\\Cybersource\\' => 20,
            'Omnipay\\Creditcall\\' => 19,
            'Omnipay\\Coinbase\\' => 17,
            'Omnipay\\CheckoutCom\\' => 20,
            'Omnipay\\Cardgate\\' => 17,
            'Omnipay\\CardSave\\' => 17,
            'Omnipay\\Buckaroo\\' => 17,
            'Omnipay\\Beanstream\\' => 19,
            'Omnipay\\AuthorizeNet\\' => 21,
            'Omnipay\\Alipay\\Tests\\' => 21,
            'Omnipay\\Alipay\\' => 15,
            'Omnipay\\Agms\\' => 13,
        ),
        'L' => 
        array (
            'League\\Url\\' => 11,
        ),
        'H' => 
        array (
            'Http\\Promise\\' => 13,
            'Http\\Client\\' => 12,
            'Http\\Adapter\\Guzzle6\\' => 21,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
            'Coatesap\\PaymentSense\\' => 22,
        ),
        'A' => 
        array (
            'Aimeos\\MShop\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'yandexmoney\\YandexMoney\\' => 
        array (
            0 => __DIR__ . '/..' . '/yandexmoney/omnipay/src',
        ),
        'TrueBV\\' => 
        array (
            0 => __DIR__ . '/..' . '/true/punycode/src',
        ),
        'Symfony\\Polyfill\\Php70\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php70',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Omnipay\\WorldPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/worldpay/src',
        ),
        'Omnipay\\Wirecard\\' => 
        array (
            0 => __DIR__ . '/..' . '/academe/omnipay-wirecard/src',
        ),
        'Omnipay\\WechatPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/lokielse/omnipay-wechatpay/src',
        ),
        'Omnipay\\WebMoney\\' => 
        array (
            0 => __DIR__ . '/..' . '/dercoder/omnipay-webmoney/src',
        ),
        'Omnipay\\WePay\\' => 
        array (
            0 => __DIR__ . '/..' . '/collizo4sky/omnipay-wepay/src',
        ),
        'Omnipay\\Veritrans\\' => 
        array (
            0 => __DIR__ . '/..' . '/andylibrian/omnipay-veritrans/src',
        ),
        'Omnipay\\UnionPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/lokielse/omnipay-unionpay/src',
        ),
        'Omnipay\\TwoCheckout\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/2checkout/src',
        ),
        'Omnipay\\TargetPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/targetpay/src',
        ),
        'Omnipay\\Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/stripe/src',
        ),
        'Omnipay\\Sisow\\' => 
        array (
            0 => __DIR__ . '/..' . '/fruitcakestudio/omnipay-sisow/src',
        ),
        'Omnipay\\Sermepa\\' => 
        array (
            0 => __DIR__ . '/..' . '/nazka/sermepa-omnipay/src',
        ),
        'Omnipay\\SecureTrading\\' => 
        array (
            0 => __DIR__ . '/..' . '/meebio/omnipay-secure-trading/src',
        ),
        'Omnipay\\SecurePay\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/securepay/src',
        ),
        'Omnipay\\SecPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/justinbusschau/omnipay-secpay/src',
        ),
        'Omnipay\\SagePay\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/sagepay/src',
        ),
        'Omnipay\\Postfinance\\' => 
        array (
            0 => __DIR__ . '/..' . '/bummzack/omnipay-postfinance/src',
        ),
        'Omnipay\\Posnet\\' => 
        array (
            0 => __DIR__ . '/..' . '/yasinkuyu/omnipay-posnet/src',
        ),
        'Omnipay\\Portmanat\\' => 
        array (
            0 => __DIR__ . '/..' . '/dercoder/omnipay-portmanat/src',
        ),
        'Omnipay\\Pin\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/pin/src',
        ),
        'Omnipay\\Paytrace\\' => 
        array (
            0 => __DIR__ . '/..' . '/softcommerce/omnipay-paytrace/src',
        ),
        'Omnipay\\Paysafecard\\' => 
        array (
            0 => __DIR__ . '/..' . '/dercoder/omnipay-paysafecard/src',
        ),
        'Omnipay\\Payone\\' => 
        array (
            0 => __DIR__ . '/..' . '/academe/omnipay-payone/src',
        ),
        'Omnipay\\PaymentWall\\' => 
        array (
            0 => __DIR__ . '/..' . '/delatbabel/omnipay-paymentwall/src',
        ),
        'Omnipay\\PaymentExpress\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/paymentexpress/src',
        ),
        'Omnipay\\Payflow\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/payflow/src',
        ),
        'Omnipay\\PayU\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/payu/src',
        ),
        'Omnipay\\PayPro\\' => 
        array (
            0 => __DIR__ . '/..' . '/paypronl/omnipay-paypro/src',
        ),
        'Omnipay\\PayPal\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/paypal/src',
        ),
        'Omnipay\\PayFast\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/payfast/src',
        ),
        'Omnipay\\Pagarme\\' => 
        array (
            0 => __DIR__ . '/..' . '/descubraomundo/omnipay-pagarme/src',
        ),
        'Omnipay\\Oppwa\\' => 
        array (
            0 => __DIR__ . '/..' . '/vdbelt/omnipay-oppwa/src',
        ),
        'Omnipay\\Novalnet\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/fruitcake/omnipay-novalnet/tests',
        ),
        'Omnipay\\Novalnet\\' => 
        array (
            0 => __DIR__ . '/..' . '/fruitcake/omnipay-novalnet/src',
        ),
        'Omnipay\\Neteller\\' => 
        array (
            0 => __DIR__ . '/..' . '/dercoder/omnipay-neteller/src',
        ),
        'Omnipay\\Netaxept\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/netaxept/src',
        ),
        'Omnipay\\NetBanx\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/netbanx/src',
        ),
        'Omnipay\\NestPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/yasinkuyu/omnipay-nestpay/src',
        ),
        'Omnipay\\NMI\\' => 
        array (
            0 => __DIR__ . '/..' . '/mfauveau/omnipay-nmi/src',
        ),
        'Omnipay\\Multicards\\' => 
        array (
            0 => __DIR__ . '/..' . '/incube8/omnipay-multicards/src',
        ),
        'Omnipay\\MultiSafepay\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/multisafepay/src',
        ),
        'Omnipay\\Mollie\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/mollie/src',
        ),
        'Omnipay\\MobilPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/business-mastery/omnipay-mobilpay/src/BusinessMastery/Mobilpay',
        ),
        'Omnipay\\Migs\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/migs/src',
        ),
        'Omnipay\\Manual\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/manual/src',
        ),
        'Omnipay\\MOLPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/leesiongchan/omnipay-molpay/src',
        ),
        'Omnipay\\Komoju\\' => 
        array (
            0 => __DIR__ . '/..' . '/vink/omnipay-komoju/src',
        ),
        'Omnipay\\Ifthenpay\\' => 
        array (
            0 => __DIR__ . '/..' . '/ifthenpay/omnipay-ifthenpay/src',
        ),
        'Omnipay\\Helcim\\' => 
        array (
            0 => __DIR__ . '/..' . '/academe/omnipay-helcim/src',
        ),
        'Omnipay\\Gvp\\' => 
        array (
            0 => __DIR__ . '/..' . '/yasinkuyu/omnipay-gvp/src',
        ),
        'Omnipay\\GoCardless\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/gocardless/src',
        ),
        'Omnipay\\GlobalAlipay\\' => 
        array (
            0 => __DIR__ . '/..' . '/lokielse/omnipay-global-alipay/src',
        ),
        'Omnipay\\GiroCheckout\\' => 
        array (
            0 => __DIR__ . '/..' . '/academe/omnipay-girocheckout/src',
        ),
        'Omnipay\\Flo2cash\\' => 
        array (
            0 => __DIR__ . '/..' . '/guisea/omnipay-flo2cash/src',
        ),
        'Omnipay\\FirstData\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/firstdata/src',
        ),
        'Omnipay\\Fatzebra\\' => 
        array (
            0 => __DIR__ . '/..' . '/delatbabel/omnipay-fatzebra/src',
        ),
        'Omnipay\\Fasapay\\' => 
        array (
            0 => __DIR__ . '/..' . '/andreas22/omnipay-fasapay/src',
        ),
        'Omnipay\\Eway\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/eway/src',
        ),
        'Omnipay\\Dummy\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/dummy/src',
        ),
        'Omnipay\\Datatrans\\' => 
        array (
            0 => __DIR__ . '/..' . '/academe/omnipay-datatrans/src',
        ),
        'Omnipay\\Cybersource\\' => 
        array (
            0 => __DIR__ . '/..' . '/dabsquared/omnipay-cybersource-soap/src',
            1 => __DIR__ . '/..' . '/dioscouri/omnipay-cybersource/src',
        ),
        'Omnipay\\Creditcall\\' => 
        array (
            0 => __DIR__ . '/..' . '/meebio/omnipay-creditcall/src',
        ),
        'Omnipay\\Coinbase\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/coinbase/src',
        ),
        'Omnipay\\CheckoutCom\\' => 
        array (
            0 => __DIR__ . '/..' . '/fotografde/omnipay-checkoutcom/src',
        ),
        'Omnipay\\Cardgate\\' => 
        array (
            0 => __DIR__ . '/..' . '/cardgate/omnipay-cardgate/src',
        ),
        'Omnipay\\CardSave\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/cardsave/src',
        ),
        'Omnipay\\Buckaroo\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/buckaroo/src',
        ),
        'Omnipay\\Beanstream\\' => 
        array (
            0 => __DIR__ . '/..' . '/lemonstand/omnipay-beanstream/src',
        ),
        'Omnipay\\AuthorizeNet\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnipay/authorizenet/src',
        ),
        'Omnipay\\Alipay\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/lokielse/omnipay-alipay/tests',
        ),
        'Omnipay\\Alipay\\' => 
        array (
            0 => __DIR__ . '/..' . '/lokielse/omnipay-alipay/src',
        ),
        'Omnipay\\Agms\\' => 
        array (
            0 => __DIR__ . '/..' . '/agmscode/omnipay-agms/src',
        ),
        'League\\Url\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/url/src',
        ),
        'Http\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/promise/src',
        ),
        'Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/httplug/src',
        ),
        'Http\\Adapter\\Guzzle6\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/guzzle6-adapter/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'Coatesap\\PaymentSense\\' => 
        array (
            0 => __DIR__ . '/..' . '/digitickets/omnipay-paymentsense/src',
        ),
        'Aimeos\\MShop\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop',
        ),
    );

    public static $prefixesPsr0 = array (
        'O' => 
        array (
            'Omnipay\\WorldPayXML\\' => 
            array (
                0 => __DIR__ . '/..' . '/teaandcode/omnipay-worldpay-xml/src',
            ),
            'Omnipay\\Sofort\\' => 
            array (
                0 => __DIR__ . '/..' . '/aimeoscom/omnipay-sofort/src',
            ),
            'Omnipay\\Skrill\\' => 
            array (
                0 => __DIR__ . '/..' . '/alfaproject/omnipay-skrill/src',
            ),
            'Omnipay\\Realex\\' => 
            array (
                0 => __DIR__ . '/..' . '/digitickets/omnipay-realex/src',
            ),
            'Omnipay\\Pacnet\\' => 
            array (
                0 => __DIR__ . '/..' . '/mfauveau/omnipay-pacnet/src',
            ),
            'Omnipay\\Komerci\\' => 
            array (
                0 => __DIR__ . '/..' . '/byjg/omnipay-komerci/src',
            ),
            'Omnipay\\Globalcloudpay\\' => 
            array (
                0 => __DIR__ . '/..' . '/dercoder/omnipay-globalcloudpay/src',
            ),
            'Omnipay\\Ecopayz\\' => 
            array (
                0 => __DIR__ . '/..' . '/dercoder/omnipay-ecopayz/src',
            ),
            'Omnipay\\DataCash\\' => 
            array (
                0 => __DIR__ . '/..' . '/digitickets/omnipay-datacash/src',
            ),
            'Omnipay\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/omnipay/common/src',
            ),
            'Omnipay\\BarclaysEpdq\\' => 
            array (
                0 => __DIR__ . '/..' . '/digitickets/omnipay-barclays-epdq/src',
            ),
        ),
        'G' => 
        array (
            'Guzzle\\Tests' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/tests',
            ),
            'Guzzle' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/src',
            ),
        ),
    );

    public static $classMap = array (
        'Aimeos\\MShop\\Service\\Provider\\Payment\\AuthorizeAIM' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/AuthorizeAIM.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\AuthorizeDPM' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/AuthorizeDPM.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\AuthorizeSIM' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/AuthorizeSIM.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\CardSave' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/CardSave.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\Datatrans' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/Datatrans.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\Mollie' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/Mollie.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\NovalnetCredit' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/NovalnetCredit.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\NovalnetSepa' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/NovalnetSepa.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\OmniPay' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/OmniPay.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\Payone' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/Payone.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\SagePay' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/SagePay.php',
        'Aimeos\\MShop\\Service\\Provider\\Payment\\Stripe' => __DIR__ . '/../../..' . '/Resources/Private/Extensions/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/Stripe.php',
        'ArithmeticError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/ArithmeticError.php',
        'AssertionError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/AssertionError.php',
        'DivisionByZeroError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/DivisionByZeroError.php',
        'Error' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/Error.php',
        'Omnipay\\Omnipay' => __DIR__ . '/..' . '/omnipay/common/src/Omnipay/Omnipay.php',
        'ParseError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/ParseError.php',
        'Paymentwall_ApiObject' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/ApiObject.php',
        'Paymentwall_ApiObjectInterface' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/ApiObjectInterface.php',
        'Paymentwall_Base' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Base.php',
        'Paymentwall_Card' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Card.php',
        'Paymentwall_Charge' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Charge.php',
        'Paymentwall_Config' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Config.php',
        'Paymentwall_GenerericApiObject' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/GenerericApiObject.php',
        'Paymentwall_HttpAction' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/HttpAction.php',
        'Paymentwall_Instance' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Instance.php',
        'Paymentwall_Mobiamo' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Mobiamo.php',
        'Paymentwall_OneTimeToken' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/OneTimeToken.php',
        'Paymentwall_Pingback' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Pingback.php',
        'Paymentwall_Product' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Product.php',
        'Paymentwall_Response_Abstract' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Response/Abstract.php',
        'Paymentwall_Response_Error' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Response/Error.php',
        'Paymentwall_Response_Factory' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Response/Factory.php',
        'Paymentwall_Response_Interface' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Response/Interface.php',
        'Paymentwall_Response_Success' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Response/Success.php',
        'Paymentwall_Signature_Abstract' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Signature/Abstract.php',
        'Paymentwall_Signature_Pingback' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Signature/Pingback.php',
        'Paymentwall_Signature_Widget' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Signature/Widget.php',
        'Paymentwall_Subscription' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Subscription.php',
        'Paymentwall_Widget' => __DIR__ . '/..' . '/paymentwall/paymentwall-php/lib/Paymentwall/Widget.php',
        'SessionUpdateTimestampHandlerInterface' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php',
        'TypeError' => __DIR__ . '/..' . '/symfony/polyfill-php70/Resources/stubs/TypeError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb1af944f0cc5ab226de341e528493365::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb1af944f0cc5ab226de341e528493365::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitb1af944f0cc5ab226de341e528493365::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitb1af944f0cc5ab226de341e528493365::$classMap;

        }, null, ClassLoader::class);
    }
}
