<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Omnipay\\WorldPayXML\\' => array($vendorDir . '/teaandcode/omnipay-worldpay-xml/src'),
    'Omnipay\\Sofort\\' => array($vendorDir . '/aimeoscom/omnipay-sofort/src'),
    'Omnipay\\Skrill\\' => array($vendorDir . '/alfaproject/omnipay-skrill/src'),
    'Omnipay\\Realex\\' => array($vendorDir . '/digitickets/omnipay-realex/src'),
    'Omnipay\\Pacnet\\' => array($vendorDir . '/mfauveau/omnipay-pacnet/src'),
    'Omnipay\\Komerci\\' => array($vendorDir . '/byjg/omnipay-komerci/src'),
    'Omnipay\\Globalcloudpay\\' => array($vendorDir . '/dercoder/omnipay-globalcloudpay/src'),
    'Omnipay\\Ecopayz\\' => array($vendorDir . '/dercoder/omnipay-ecopayz/src'),
    'Omnipay\\DataCash\\' => array($vendorDir . '/digitickets/omnipay-datacash/src'),
    'Omnipay\\Common\\' => array($vendorDir . '/omnipay/common/src'),
    'Omnipay\\BarclaysEpdq\\' => array($vendorDir . '/digitickets/omnipay-barclays-epdq/src'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
);
