<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Zend\\Diactoros\\' => array($vendorDir . '/zendframework/zend-diactoros/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib/Doctrine/Common/Lexer'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib/Doctrine/Common'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Aimeos\\MW\\' => array($baseDir . '/Resources/Private/Extensions/ai-admin-jqadm/lib/custom/src/MW', $baseDir . '/Resources/Private/Extensions/ai-gettext/lib/mwlib/src/MW', $baseDir . '/Resources/Private/Extensions/ai-typo3/lib/custom/src/MW', $vendorDir . '/aimeos/aimeos-core/lib/mwlib/src/MW'),
    'Aimeos\\MShop\\' => array($baseDir . '/Resources/Private/Extensions/ai-typo3/lib/custom/src/MShop', $vendorDir . '/aimeos/aimeos-core/lib/mshoplib/src/MShop'),
    'Aimeos\\MAdmin\\' => array($vendorDir . '/aimeos/aimeos-core/lib/mshoplib/src/MAdmin'),
    'Aimeos\\Controller\\Jobs\\' => array($baseDir . '/Resources/Private/Extensions/ai-client-html/controller/jobs/src/Controller/Jobs', $baseDir . '/Resources/Private/Extensions/ai-controller-jobs/controller/jobs/src/Controller/Jobs', $vendorDir . '/aimeos/aimeos-core/controller/common/src/Controller/Jobs'),
    'Aimeos\\Controller\\Frontend\\' => array($baseDir . '/Resources/Private/Extensions/ai-controller-frontend/controller/frontend/src/Controller/Frontend'),
    'Aimeos\\Controller\\Common\\' => array($baseDir . '/Resources/Private/Extensions/ai-client-html/controller/common/src/Controller/Common', $baseDir . '/Resources/Private/Extensions/ai-controller-jobs/controller/jobs/src/Controller/Common', $vendorDir . '/aimeos/aimeos-core/controller/common/src/Controller/Common'),
    'Aimeos\\Client\\JsonApi\\' => array($baseDir . '/Resources/Private/Extensions/ai-client-jsonapi/client/jsonapi/src/Client/JsonApi'),
    'Aimeos\\Client\\Html\\' => array($baseDir . '/Resources/Private/Extensions/ai-client-html/client/html/src/Client/Html'),
    'Aimeos\\Aimeos\\' => array($baseDir . '/Classes'),
    'Aimeos\\Admin\\Jsonadm\\' => array($baseDir . '/Resources/Private/Extensions/ai-admin-jsonadm/admin/jsonadm/src/Admin/Jsonadm'),
    'Aimeos\\Admin\\JQAdm\\' => array($baseDir . '/Resources/Private/Extensions/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm'),
    'Aimeos\\' => array($vendorDir . '/aimeos/aimeos-core'),
);
