# sudo: required

language: php

# services:
#   - docker

php:
  - 5.6
  - 7.0
  - 7.1
  # - 7.2

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
  - vendor/bin/phpunit --coverage-text
