<?php
return [
    'BE' => [
        'allowDonateWindow' => '0',
        'debug' => false,
        'disable_exec_function' => '0',
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$P$CJOI8eA9VcaQuJIUs7Q.L13ys4V3CF1',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'database' => 't3d_db',
        'extTablesDefinitionScript' => 'extTables.php',
        'host' => 'localhost',
        'password' => 'K}S`%_2L+4{q@0;K>?vw',
        'socket' => '',
        'username' => 't3d_db_usr',
    ],
    'EXT' => [
        'extConf' => [
            'aimeos' => 'a:10:{s:8:"siteCode";s:7:"default";s:7:"siteTpl";s:7:"default";s:9:"autoSetup";s:1:"1";s:7:"cleanDb";s:1:"1";s:11:"useDemoData";s:0:"";s:20:"useRealUrlAutoConfig";s:1:"1";s:9:"cacheName";s:5:"Typo3";s:6:"useAPC";s:1:"0";s:9:"apcPrefix";s:3:"t3:";s:12:"showPageTree";s:1:"0";}',
            'aimeos_pay' => 'a:0:{}',
            'automaketemplate' => 'a:0:{}',
            'backend' => 'a:3:{s:9:"loginLogo";s:30:"fileadmin/anmeldung/megura.jpg";s:19:"loginHighlightColor";s:0:"";s:20:"loginBackgroundImage";s:33:"fileadmin/anmeldung/anmeldung.jpg";}',
            'belog' => 'a:0:{}',
            'beuser' => 'a:0:{}',
            'bootstrap_grids' => 'a:1:{s:19:"enableGridSimpleRow";s:1:"0";}',
            'cl_jquery_fancybox' => 'a:0:{}',
            'compatibility6' => 'a:1:{s:15:"setPageTSconfig";s:1:"1";}',
            'em' => 'a:1:{s:17:"selectedLanguages";s:2:"de";}',
            'form' => 'a:0:{}',
            'frey_aimeos' => 'a:0:{}',
            'go_maps_ext' => 'a:3:{s:15:"include_library";s:1:"0";s:16:"include_manually";s:1:"0";s:8:"footerJS";s:1:"1";}',
            'gridelements' => 'a:3:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";s:26:"overlayShortcutTranslation";s:1:"0";}',
            'imagecycle' => 'a:7:{s:7:"effects";s:233:",none,blindX,blindY,blindZ,cover,curtainX,curtainY,fade,fadeout,fadeZoom,growX,growY,scrollUp,scrollDown,scrollLeft,scrollRight,scrollHorz,scrollVert,shuffle,slideX,slideY,toss,turnUp,turnDown,turnLeft,turnRight,uncover,wipe,zoom,all";s:11:"effectsCoin";s:27:",random,swirl,rain,straight";s:11:"effectsNivo";s:178:",random,sliceDown,sliceDownLeft,sliceUp,sliceUpLeft,sliceUpDown,sliceUpDownLeft,fold,fade,slideInRight,slideInLeft,boxRandom,boxRain,boxRainReverse,boxRainGrow,boxRainGrowReverse";s:15:"nivoThemeFolder";s:34:"EXT:imagecycle/res/css/nivoslider/";s:24:"useSelectInsteadCheckbox";s:1:"0";s:24:"allowedDbTypesForCaption";s:0:"";s:13:"updateMessage";s:1:"0";}',
            'indexed_search' => 'a:17:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
            'jh_magnificpopup' => 'a:2:{s:19:"colPosOfIrreContent";s:3:"109";s:19:"enableAlphaFeatures";s:1:"0";}',
            'maag_randomimage' => 'a:0:{}',
            'news' => 'a:16:{s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"1";s:21:"contentElementPreview";s:1:"1";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:0:"";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"dateTimeNotRequired";s:1:"0";s:11:"archiveDate";s:4:"date";s:12:"mediaPreview";s:5:"false";s:24:"showAdministrationModule";s:1:"1";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";}',
            'ns_ext_compatibility' => 'a:1:{s:18:"typo3TargetVersion";s:4:"11.x";}',
            'nwt_imagecrop' => 'a:0:{}',
            'perfectlightbox' => 'a:0:{}',
            'pit_googlemaps' => 'a:0:{}',
            'powermail' => 'a:16:{s:12:"disableIpLog";s:1:"0";s:27:"disableMarketingInformation";s:1:"1";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:35:"disablePluginInformationMailPreview";s:1:"0";s:13:"enableCaching";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";s:28:"enableTableGarbageCollection";s:1:"0";s:10:"usePreview";s:1:"1";s:12:"cssSelection";s:1:"1";s:14:"feusersPrefill";s:70:"name, address, telephone, fax, email, zip, city, country, www, company";s:12:"disableIPlog";s:1:"0";s:16:"disableStartStop";s:1:"0";s:7:"useIRRE";s:1:"1";s:12:"fileToolPath";s:9:"/usr/bin/";}',
            'realurl' => 'a:6:{s:10:"configFile";s:30:"typo3conf/realurl_autoconf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rtehtmlarea' => 'a:13:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:16:"enableDAMBrowser";s:1:"0";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:0;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'seo_basics' => 'a:1:{s:10:"xmlSitemap";s:1:"1";}',
            'sg_contentlink' => 'a:0:{}',
            'static_info_tables' => 'a:1:{s:13:"enableManager";s:1:"0";}',
            't3jquery' => 'a:14:{s:15:"alwaysIntegrate";s:1:"1";s:17:"integrateToFooter";s:1:"0";s:17:"enableStyleStatic";s:1:"0";s:18:"dontIntegrateOnUID";s:0:"";s:23:"dontIntegrateInRootline";s:1:"1";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:5:"2.1.x";s:15:"jQueryUiVersion";s:0:"";s:18:"jQueryTOOLSVersion";s:0:"";s:22:"jQueryBootstrapVersion";s:0:"";s:16:"integrateFromCDN";s:1:"1";s:11:"locationCDN";s:6:"google";s:13:"updateMessage";s:1:"0";}',
            'tt_news' => 'a:15:{s:13:"useStoragePid";s:1:"0";s:13:"noTabDividers";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:13:"prependAtCopy";s:1:"1";s:17:"requireCategories";s:1:"0";s:5:"label";s:5:"title";s:9:"label_alt";s:8:"datetime";s:10:"label_alt2";s:5:"short";s:15:"label_alt_force";s:1:"0";s:11:"treeOrderBy";s:5:"title";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:18:"categoryTreeHeigth";s:1:"5";}',
            'ws_flexslider' => 'a:0:{}',
            'ws_scss' => 'a:0:{}',
            'wt_spamshield' => 'a:10:{s:12:"useNameCheck";s:1:"0";s:12:"usehttpCheck";s:1:"3";s:9:"notUnique";s:0:"";s:13:"honeypodCheck";s:1:"1";s:15:"useSessionCheck";s:1:"1";s:16:"SessionStartTime";s:2:"10";s:14:"SessionEndTime";s:3:"600";s:10:"AkismetKey";s:0:"";s:12:"email_notify";s:0:"";s:3:"pid";s:2:"-1";}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'FE' => [
        'cHashIncludePageId' => '1',
        'debug' => false,
        'pageNotFound_handling' => 'http://www.hp-frey.ch/index.php?id=120',
    ],
    'GFX' => [
        'colorspace' => 'sRGB',
        'gdlib_png' => '1',
        'im' => '1',
        'im_mask_temp_ext_gif' => '1',
        'im_path' => '/usr/local/bin/',
        'im_path_lzw' => '/usr/local/bin/',
        'im_v5effects' => '0',
        'im_version_5' => 'im6',
        'image_processing' => '1',
        'jpg_quality' => '80',
    ],
    'HTTP' => [
        'adapter' => 'curl',
    ],
    'INSTALL' => [
        'wizardDone' => [
            'TYPO3\CMS\Install\Updates\AccessRightParametersUpdate' => 1,
            'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\Compatibility6ExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListInAccessModuleListUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListIsStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FilesReplacePermissionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MigrateMediaToAssetsForTextMediaCe' => 1,
            'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsAgainUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\DeprecatedRteProperties' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\RteAcronymButtonRenamedToAbbreviation' => 1,
            'tx_coreupdates_installnewsysexts' => '1',
            'tx_rtehtmlarea_deprecatedRteProperties' => '1',
        ],
    ],
    'MAIL' => [
        'transport_sendmail_command' => '',
    ],
    'SYS' => [
        'UTF8filesystem' => '0',
        'clearCacheSystem' => false,
        'curlUse' => '1',
        'devIPmask' => '',
        'displayErrors' => 0,
        'enableDeprecationLog' => false,
        'encryptionKey' => 'c9fe887beed5c9eb3eaeea5a7f7b6fe4',
        'fileCreateMask' => '0664',
        'folderCreateMask' => '2775',
        'sitename' => 'H.P. Frey Gartenbau',
        'sqlDebug' => 0,
        'systemLogLevel' => 2,
        't3lib_cs_convMethod' => 'mbstring',
        't3lib_cs_utils' => 'mbstring',
    ],
];
