<?php
return array(
	'BE' => array(
		'allowDonateWindow' => '0',
		'disable_exec_function' => '0',
		'fileCreateMask' => '0664',
		'folderCreateMask' => '2775',
		'forceCharset' => 'utf-8',
		'installToolPassword' => 'edef9fb36f3679cc8b338900307c4ce4',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'freytpdreidb',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'localhost',
		'password' => '0t4PiNUnSzcsfT7hXK8G',
		'username' => 'usr_hpftypo3',
	),
	'EXT' => array(
		'extConf' => array(
			'em' => 'a:1:{s:17:"selectedLanguages";s:2:"de";}',
			'indexed_search' => 'a:17:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'powermail' => 'a:8:{s:10:"usePreview";s:1:"1";s:12:"cssSelection";s:1:"1";s:14:"feusersPrefill";s:70:"name, address, telephone, fax, email, zip, city, country, www, company";s:12:"disableIPlog";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:16:"disableStartStop";s:1:"0";s:7:"useIRRE";s:1:"1";s:12:"fileToolPath";s:9:"/usr/bin/";}',
			'realurl' => 'a:4:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"1";s:12:"enableDevLog";s:1:"0";}',
			'rtehtmlarea' => 'a:13:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"enableDAMBrowser";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";}',
			'tt_news' => 'a:15:{s:13:"useStoragePid";s:1:"0";s:13:"noTabDividers";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:13:"prependAtCopy";s:1:"1";s:17:"requireCategories";s:1:"0";s:5:"label";s:5:"title";s:9:"label_alt";s:8:"datetime";s:10:"label_alt2";s:5:"short";s:15:"label_alt_force";s:1:"0";s:11:"treeOrderBy";s:5:"title";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:18:"categoryTreeHeigth";s:1:"5";}',
			'wt_spamshield' => 'a:10:{s:12:"useNameCheck";s:1:"0";s:12:"usehttpCheck";s:1:"3";s:9:"notUnique";s:0:"";s:13:"honeypodCheck";s:1:"1";s:15:"useSessionCheck";s:1:"1";s:16:"SessionStartTime";s:2:"10";s:14:"SessionEndTime";s:3:"600";s:10:"AkismetKey";s:0:"";s:12:"email_notify";s:0:"";s:3:"pid";s:2:"-1";}',
		),
		'extListArray' => array(
			'extbase',
			'css_styled_content',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'indexed_search',
			'introduction',
			'automaketemplate',
			'realurl',
			'wt_spamshield',
			'info',
			'perm',
			'func',
			'filelist',
			'pit_googlemaps',
			'perfectlightbox',
			'maag_randomimage',
			'fluid',
			'version',
			'workspaces',
		),
		'extList_FE' => 'extbase,css_styled_content,install,rtehtmlarea,t3skin,felogin,indexed_search,introduction,automaketemplate,realurl,wt_spamshield,pit_googlemaps,perfectlightbox,maag_randomimage,fluid,version,workspaces',
	),
	'GFX' => array(
		'TTFdpi' => '96',
		'colorspace' => 'sRGB',
		'gdlib_png' => '1',
		'im' => '1',
		'im_combine_filename' => 'composite',
		'im_imvMaskState' => '1',
		'im_negate_mask' => '0',
		'im_path' => '/usr/local/bin/',
		'im_path_lzw' => '/usr/local/bin/',
		'im_version_5' => 'im6',
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'tx_coreupdates_installnewsysexts' => '1',
			'tx_coreupdates_installsysexts' => '1',
			'tx_rtehtmlarea_deprecatedRteProperties' => '1',
		),
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'compat_version' => '4.7',
		'curlUse' => '1',
		'encryptionKey' => 'c9fe887beed5c9eb3eaeea5a7f7b6fe4',
		'setDBinit' => 'SET NAMES utf8;',
		'sitename' => 'New TYPO3 site',
	),
);
?>