<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frey_aimeos"
 *
 * Auto generated by Extension Builder 2014-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'frey_aimeos',
	'description' => 'Aimeos TYPO3 extension for frey_aimeos project',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
			'aimeos' => '18.1.0-18.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);